---
title: "ITIL v4 e a cadeia de valor"
description: "ITIL v4 - Conceitos de valor e cadeia de valor"
date: 2022-11-25
author: 
  - name: Marcos Abreu
    url: https://abreums.github.io
    orcid: 0000-0003-4772-7955
citation:
  type: post-weblog
  url: https://abreums.github.io/posts/2022-11-25-itil-cadeia-de-valor/
  language: pt-br
categories: [Gestão]
---

**ITIL** - *Information Technology Infrastructure Library*

Recentemente fui convidado para ministrar curso sobre a ITIL versão 4.

Confesso que nunca fui grande entusiasta da ITIL, apesar de reconhecer o valor que ela possui. As minhas restrições se devem a todas os sistemas que buscam ser um modelo "completo" de determinado assunto. E isto não é característica apenas da ITIL, mas de outros modelos também.

Qual o problema em tentar criar um modelo completo?

O problema é cair no erro que é tão bem descrito por Luis Carlos Borges em seu poema *Del rigor de la ciencia*, que pode ser lido na tradução para o portugês neste [link](https://cosmosecontexto.org.br/do-rigor-da-ciencia/), ou na sua versão original em espanhol lido pelo próprio Borges neste [vídeo no Youtube](https://www.youtube.com/watch?v=zwDA3GmcwJU).

Apesar das minhas restrições em relação aos sistemas que tentam ser "completos", encontrei nesta versão 4 da ITIL destaque para um tema que tenho muito apreço. E particularmente considero o destaque dado pela ITIL v4 a este tema adequado. Estou me referindo ao conceito de **valor**.

## Valor e Utilidade

Se existe um conceito que considero útil para o desenvolvimento de sistemas de software e particularmente para o gerenciamento e priorização de projetos é o de *Utilidade marginal*. E neste caso, me refiro explicitamente à definição conforme tratada pelos economistas.

Sugiro uma busca na [Wikipedia](https://pt.wikipedia.org/wiki/Hist%C3%B3ria_do_pensamento_econ%C3%B3mico#Utilidade_marginal) sobre temas como [História do Pensamento Econômico e Utilidade Marginal](https://pt.wikipedia.org/wiki/Hist%C3%B3ria_do_pensamento_econ%C3%B3mico#Utilidade_marginal), ou [Lei da Utilidade Marginal](https://pt.wikipedia.org/wiki/Lei_da_utilidade_marginal), ou ainda [Paradoxo da água e do diamante](https://pt.wikipedia.org/wiki/Paradoxo_da_%C3%A1gua_e_do_diamante).

Mas se você ainda não se convenceu da importância do tema e não está com vontade de ir atrás dos links acima, aqui vai minha explicação do motivo pelo qual este conceito é importante para a gestão da TI ou para o sucesso dos seus projetos.

Um dos desafios que temos quando estamos lidando com projetos de TI é o da priorização. O problema está na escolha do que deve ser considerado mais importante. Em geral, para o negócio, **tudo é importante**.

Aqui entra a teoria da Utilidade Marginal. Primeiro é preciso distinguir valor de utilidade: um copo d'água é util para matar a cede. Se você está no conforto da sua casa e já se hidratou com um pouco de café ou chá, o valor de um copo d'água é muito baixo. Mas, se você está perdido no deserto há 5 dias sem beber água, o valor de um copo d'água é absurdamente alto.

Em projetos, ou na gestão da TI, se passa a mesma coisa. É óbvio que a funcionalidade de "Emissão de Nota Fiscal" é útil tanto quanto muitas outras funcionalidades que suportam o negócio. Podemos dizer que **tudo é útil**. Mas dentro do contexto de um projeto, se ainda sequer temos uma base de informações de clientes disponível, a disponibilização da base de clientes possui - neste momento - maior valor que a funcionalidade de emissão de nota fiscal. É o contexto que atribui valor. E durante um projeto, o contexto muda.

## Cadeia de Valor

A ITIL v4 definie princípios que devem guiar a ação da TI nas empresas, e o princípio número 1 é "Foco no valor".

Também a forma como a discussão sobre valor é desenvolvida merece destaque.

A visão de que a TI (ou uma organização) gera valor para seus clientes semelhante ao processo como uma empresa de encomendas entrega um pacote para um destinatário é bastante limitada, e restrita ao conceito de que um lado gera valor e outro consome.

Esta visão por exemplo, exclui o consumidor do próprio processo de criação de valor, e não reflete toda a complexidade que existe na relação entre as duas partes.

Hoje, há reconhecimento de que o valor é uma criação conjunta entre fornecedor e receptor, e também de outras partes que atuam no processo. E esta visão de que o valor é uma construção coletiva e constante (porque muda) é a base para o conceito de **cadeia de valor** (*value chain*) na ITIL v4.

Ao meu ver, foi uma contribuição significativa da ITIL e uma mudança importante para a gestão da Tecnologia da Informação. Abre espaço para discutirmos e avaliarmos alternativas nos meios e formas como podemos construir este valor.
