{
  "hash": "02b6d441dcdf45c07e851a0bc5c9ee57",
  "result": {
    "markdown": "---\ntitle: \"Distribuição Poisson\"\ndescription: \"Alguns exemplos de comom usar a distribuição de Poisson e como calcular com R\"\ndate: 2022-02-26\nauthor: \n  - name: Marcos Abreu\n    url: https://abreums.github.io\n    orcid: 0000-0003-4772-7955\ncitation:\n  type: post-weblog\n  url: https://abreums.github.io/posts/2022-02-26-poisson/\n  language: pt-br\nimage: \"poisson.png\"\ncategories: [Rstat]\n---\n\n\nA distribuição Poisson é utilizada para aplicações onde a contagem do número de sucessos é um grande número de tentativas mas a probabilidade de sucesso de cada tentativa é pequena.\n\nAs condições para uso da distribuição de Poisson incluem:\n\n-   k é o número positivo de vezes que um evento acontece dentro de um período de tempo. O valor de k deve ser algo como: 0, 1, 2, 3, 4, etc.\n\n-   A ocorrência de um evento não afeta a re-ocorrência do evento, ou seja, os evento ocorrem independentemente. Uma fraca dependência é aceitável principalmente quando o número de eventos é grande.\n\n-   O evento em análise não pode ocorrer duas vezes no mesmo momento.\n\n-   A probabilidade de um evento ocorrer em uma pequena parte do intervalo de tempo analisado é proporcional ao tamanho da pequena parte do intervalo.\n\n-   O número de tentativas é consideravelmente maior do que o número de vezes que o evento ocorre.\n\n## Fórmula\n\nA fórmula da distribuição de Poisson é:\n\n$$\nP(x,\\mu) = \\frac{e^{-\\mu}\\mu^x}{x!}  \n$$\n\nOnde,\n\nx = número de vezes em que o evento ocorre durante um período de tempo\n\n$\\mu$ = média de ocorrência do evento.\n\ne = constante de Euler, aproximadamente 2,71828\n\nExemplo 1:\n\nConsidere que o número médio de vendas de um determinado modelo de televisão numa cadeia de lojas é de 5 aparelhos por dia.\n\nQual é a probabilidade de serem vendidos 9 aparelhos no dia de hoje?\n\n$$\n\\begin{align}\nP(x, \\mu) & = \\\\\n& = P(9, 5) = \\\\\n& = \\frac{e^{-5} 5^{9}}{9!} = \\\\\n& = 0.036\n\\end{align}\n$$\n\nUtilizando R:\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n#| warning: false\n#| error: false\n#| message: false\n\ndpois(x = 9, lambda = 5)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03626558\n```\n:::\n:::\n\n\nExemplo 2:\n\nUma lanchonete recebe em média 2.8 clientes por minuto.\n\nConsiderando que o número de clientes que chegam na lanchonete segue uma distribuição Poisson, qual é a probabilidade de 4 clientes chegarem no próximo minuto?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(4, 2.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1557386\n```\n:::\n:::\n\n\n$$\n\\begin{align}\nP(4, 2.8) & = \\\\\n& = \\frac{e^{2.8} * 2.8^4}{4!} \\\\\n& = 0.15573  \\\\\n& = 15.5\\%\n\\end{align}\n$$\n\nExample 3:\n\nA distribuição de Poisson pode ser utilizada para calcular a probabilidade de \"mais do que\" ou \"menos que\" utilizando a regra da soma e as probabilidades complementares.\n\nFoi registrado que um cruzamento registra 1.6 carros chegando por minuto.\n\nQual a probabilidade que 3 ou mais carros cheguem no cruzamento em um determinado minuto?\n\nNeste caso, queremos:\n\n$$\nP(X \\geq 3)\n$$\ncom:\n$$\nk = 3  \\\\\n\\lambda =  1.6\n$$\n\nComo não há limite superior para k, este valor não pode ser calculado diretamente. Entretanto, podemos calcular a $P(X \\leq 2)$ e obter seu complemento.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np0 = dpois(0,1.6)\np0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2018965\n```\n:::\n\n```{.r .cell-code}\np1 = dpois(1,1.6)\np1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3230344\n```\n:::\n\n```{.r .cell-code}\np2 = dpois(2,1.6)\np2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2584275\n```\n:::\n\n```{.r .cell-code}\np = p0 + p1 + p2\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7833585\n```\n:::\n\n```{.r .cell-code}\n1-p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2166415\n```\n:::\n\n```{.r .cell-code}\n# ou\nppois(2, 1.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7833585\n```\n:::\n:::\n\n\n$$\nP(X \\geq 3) = 1 - P(X \\leq 2) \\approx 0.2166\n$$\n\nou:\n\n$$\n21.7\\%\n$$\n\nExemplo 4:\n\nUm call-center recebe uma média de 4,5 chamadas a cada 5 minutos. Cada atendente consegue atender uma destas chamadas no período de 5min. Se uma chamada chega ao call-center e não há atendentes disponíveis, a chamada é colocada em espera.\n\nQual o número mínimo de atendentes que devem estar trabalhando para que o número de chamadas colocadas em espera não seja maior do que 10% do tempo.\n\nP(X \\> k) \\< 0.1\n\nPara resolver esta questão primeiro temos a constatação de que para uma chamada ficar em espera o número de chamadas recebidas deverá ser maior do que o número de atendentes.\n\nSe X é o número de chamadas recebidas e k o número de atendentes, então k deve ser determinado de forma que:\n\n$P(X > k) \\leq 0.1$\n\nou equivalentemente:\n\n$P(X \\leq k) > 0.9$\n\nO número médio de chamadas é 4,5 ou seja:\n\n$\\lambda = 4.5$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p0 = dpois(0, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.011109\n```\n:::\n\n```{.r .cell-code}\n(p1 = dpois(1, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04999048\n```\n:::\n\n```{.r .cell-code}\n(p2 = dpois(2, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1124786\n```\n:::\n\n```{.r .cell-code}\n(p3 = dpois(3, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1687179\n```\n:::\n\n```{.r .cell-code}\n(p4 = dpois(4, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1898076\n```\n:::\n\n```{.r .cell-code}\n(p5 = dpois(5, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1708269\n```\n:::\n\n```{.r .cell-code}\n(p6 = dpois(6, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1281201\n```\n:::\n\n```{.r .cell-code}\n(p7 = dpois(7, 4.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.08236295\n```\n:::\n\n```{.r .cell-code}\n1-p7\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9176371\n```\n:::\n\n```{.r .cell-code}\n# ou\nppois(7, 4.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9134135\n```\n:::\n:::\n\n\n$P(X = 7) \\approx 0.0823 \\implies P(X \\leq 7) \\approx 0.913$\n\nSe o objetivo é que menos de 10% das chamadas fiquem em espera, então ao menos 7 atendentes devem ser colocados em serviço.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}