---
title: "História do Pensamento Econômico - Adam Smith"
author: "Marcos Abreu"
date: "2019-05-01"
categories: [news]
---

Seguem alguns pensamentos sobre Adam Smith e sua obra.

1.  Principais conceitos:

-   iluminismo:
-   The theory of moral sentiments:
-   The wealth of nations:
-   mão invisível:
-   divisão do trabalho:
-   lei da vantagem absoluta no mercado internacional:
-   paradoxo água-diamante:
-   teoria do valor do custo do trabalho
-   teoria do valor controlado pelo trabalho:
-   doutrina das reservas de salários:
-   diferencas de equalização de salário:
-   ampliação do mercado:
-   acúmulo de capital:

2.  Qual o tema geral de Theory of moral sentiments, de Smith? Como esta relacionada com The Wealth of Nations?

3.  Como o titulo do tratado de Smith sobre as economias se relaciona com sua crítica ao mercantilismo? Como Smith define a riqueza das nações? Quais fatores se interagem para ocasionar aumentos na riqueza da nações?

4.  Explique o principal apontamento que Smith estava tentando fazer por meio de sua descrição da fábrica de alfinetes. Como essa descricao esta relacionada ao seu pedido por escolas públicas?

5.  Em quais circunsdncias Smith poderia ser chamado de um defensor do laissez-faire? Sobre quais bases alguem poderia contestar esse rOtulo?

6.  Como, de acordo com Smith, o bem social pode resultar da busca do interesse prOprio do individuo? Relate essa nNa-o para os modelos graficos no longo e curto prazos de um mercado de produtos perfeitamente competitivo. (Se necessario, releia um texto de principios econOmicos.)

7.  De acordo com Smith, o que determina o valor de troca em uma economia primia? 0 que determina o valor de troca em uma economia desenvolvida? Por que Smith preferiu utilizar \`controlado pelo trabalho" a "controlado pela moeda" como uma medida do valor de um bem?

8.  0 prN o natural definido por Smith e controlado pela oferta, pela demanda ou por ambas?

Explique detalhadamente. 9. Por que a divisk) do trabalho ocasiona o aumento do aciimulo de capital (seta a da Figura 5-1), de acordo com Smith? Os economistas atuais incluiriam tambem uma seta oposta do controle do actimulo de capital para a divisaTo do trabalho. Explique por meio de exemplos atuais. 10. 0 que é um salario de eficiencia? Qual a func-ao desses salarios na teoria de desenvolvimento econOmico de Smith? Como os salarios de eficiencia poderiam contribuir para elevar as taxas de desemprego friccional e para as recessOes, de acordo com as teorias modernas sobre os salarios de eficiencia? 11. Voce concorda com a seguinte afirmac'ao: Adam Smith recorre justamente aos muitos eco- nomistas contempor'aneos porque, como Smith, eles tem uma concep o da natureza hu- r.ctrit-n?
